[package]
name = "driver_tikv_server"
version = "0.1.0"
authors = ["Brian Anderson <andersrb@gmail.com>"]
edition = "2018"

[lib]
path = "driver_tikv_server.rs"

[dependencies]
b_error = "0.1.0"
clap = "2.32"
tikv = { path = "../tikv" }
toml = "0.4"
